version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: empresa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5433:5432"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empresa
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/empresa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - postgres
